language: node_js
node_js: 14

install:
    - yarn
    - yarn global add semantic-release  @semantic-release/changelog  @semantic-release/git conventional-changelog-cmyr-config
script:
    - npm run lint
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - semantic-release
cache:
    directories:
        - node_modules
